// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwjBDDegCJ5PbFGKasjcZm13DZrnuCNFA',
    appId: '1:630064020417:web:11ce8a1fabe6136cc3cd40',
    messagingSenderId: '630064020417',
    projectId: 'statera-0',
    authDomain: 'statera-0.firebaseapp.com',
    storageBucket: 'statera-0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCluuse8EMgjpaLfVcO69z3esNMyR0KtQo',
    appId: '1:630064020417:android:b5225bd258a8b7c9c3cd40',
    messagingSenderId: '630064020417',
    projectId: 'statera-0',
    storageBucket: 'statera-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9aCDTXfF-LiSwaRS8OryLJMM9scjGirY',
    appId: '1:630064020417:ios:1aea53600307ad40c3cd40',
    messagingSenderId: '630064020417',
    projectId: 'statera-0',
    storageBucket: 'statera-0.appspot.com',
    androidClientId: '630064020417-8uv3u5p6kg4ja8req6svs5edfmv15htq.apps.googleusercontent.com',
    iosClientId: '630064020417-3r46lh80ajgs92ovhc52rh04emg40b75.apps.googleusercontent.com',
    iosBundleId: 'com.statera.statera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9aCDTXfF-LiSwaRS8OryLJMM9scjGirY',
    appId: '1:630064020417:ios:1aea53600307ad40c3cd40',
    messagingSenderId: '630064020417',
    projectId: 'statera-0',
    storageBucket: 'statera-0.appspot.com',
    androidClientId: '630064020417-8uv3u5p6kg4ja8req6svs5edfmv15htq.apps.googleusercontent.com',
    iosClientId: '630064020417-3r46lh80ajgs92ovhc52rh04emg40b75.apps.googleusercontent.com',
    iosBundleId: 'com.statera.statera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwjBDDegCJ5PbFGKasjcZm13DZrnuCNFA',
    appId: '1:630064020417:web:11ce8a1fabe6136cc3cd40',
    messagingSenderId: '630064020417',
    projectId: 'statera-0',
    authDomain: 'statera-0.firebaseapp.com',
    storageBucket: 'statera-0.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAwjBDDegCJ5PbFGKasjcZm13DZrnuCNFA',
    appId: '1:630064020417:web:63c1accb48fd54d2c3cd40',
    messagingSenderId: '630064020417',
    projectId: 'statera-0',
    authDomain: 'statera-0.firebaseapp.com',
    storageBucket: 'statera-0.appspot.com',
  );
}
