# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end

  desc "CI - install certificates and provisioning profiles"
  lane :ci_build_ipa do |options|
    setup_ci

    export_method = options[:export_method] || "development"
    match(type: export_method)
  end

  lane :upload_to_testflight do |options|
    path = options[:path] 
    if !File.exist?("../#{path}")
        throw "File not found at path: #{path}"
    end

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_API_KEY_BASE_64"],
      is_key_content_base64: true
    )

    upload_to_testflight(
      apple_id: ENV["APP_STORE_CONNECT_APPLE_ID"],
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      ipa: path
    )
  end
end
