# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Create draft release on Google Play"
  lane :release do |options|
    upload_to_play_store(
      skip_upload_changelogs: true,
      version_name: options[:version_name],
      aab: options[:aab],
    )
  end

  desc "Create App Distribution release"
  lane :upload_to_firebase_app_distribution do |options|
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_type: "AAB",
      android_artifact_path: options[:android_artifact_path] || "../build/app/outputs/bundle/release/app-release.aab",
      groups: "friends",
      debug: true
    )
  end
end
