name: Build artifact and create draft release

on:
  workflow_dispatch:
     
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  web-build-artifact:
    name: Build Web Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Copy .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV > .env

      - name: Get dependencies
        run: flutter pub get

      - name: Build project
        run: flutter build web
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-out
          path: build/web
  
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: web-build-artifact
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-out
          path: web.out

      - name: Zip Artifact
        run: |
          zip -r web.out.zip web.out

      - name: Read Version
        id: read-version
        uses: jbutcher5/read-yaml@1.6
        with:
          file: pubspec.yaml
          key-path: '["version"]'

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.read-version.outputs.data }}
          name: Release ${{ steps.read-version.outputs.data }} (from run ${{ github.run_number }})
          body: |
            ## Release Notes
            
            <Please provie release notes here>
          draft: true
          files: web.out.zip
  
  # deploy-android:
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - name: Get version bump from PR label
  #       id: bump
  #       uses: rymndhng/release-on-push-action@master
  #       with:
  #         # gets overriden by PR label
  #         bump_version_scheme: minor
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Download Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'

  #     - name: Download Flutter
  #       uses: subosito/flutter-action@v1
  #       with:
  #         channel: 'stable'

  #     - name: Copy google-services.json
  #       env:
  #         FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  #       run: echo $FIREBASE_CONFIG > android/app/google-services.json

  #     - name: Copy keystore
  #       env:
  #         KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
  #       run: echo $KEYSTORE_BASE64 | base64 -d > android/app/upload-keystore.jks

  #     - name: Copy keystore properties
  #       env:
  #         KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
  #       run: echo $KEY_PROPERTIES > android/key.properties

  #     - name: Get dependencies
  #       run: flutter pub get

  #     - name: Build project
  #       run: flutter build apk

  #     - name: Attach release APK
  #       uses: ncipollo/release-action@v1
  #       with:
  #         allowUpdates: true
  #         artifacts: "build/app/outputs/apk/release/app-release.apk"
  #         token: '${{ secrets.GITHUB_TOKEN }}'
  #         tag: ${{ steps.bump.outputs.tag_name }}
