name: Build artifacts and create draft release

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  web-build-artifact:
    name: Build Web Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Java
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 14

      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Copy .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV > .env

      - name: Get dependencies
        run: flutter pub get

      - name: Build project
        run: flutter build web

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-out
          path: build/web

  android-build-artifact:
    name: Build Android Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Java
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 14

      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Copy .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV > .env

      - name: Get dependencies
        run: flutter pub get

      - name: Copy google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > android/app/google-services.json

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: Build App bundle
        run: flutter build appbundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-out
          path: build/app/outputs/bundle/release/app-release.aab

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - web-build-artifact
      - android-build-artifact
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download All Artifacts
        uses: actions/download-artifact@v3

      - run: ls -R

      - name: Zip Web Artifact
        run: |
          cd web-out
          zip -r ../web.zip .
          cd ..

      - name: Rename Android Artifact
        run: mv android-out/app-release.aab ./android.aab

      - name: Read Version
        id: read-version
        uses: jbutcher5/read-yaml@1.6
        with:
          file: pubspec.yaml
          key-path: '["version"]'

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.read-version.outputs.data }}_${{ github.run_number }}
          name: Release ${{ steps.read-version.outputs.data }} (from run ${{ github.run_number }})
          body: |
            ## Release Notes

            <Please provide release notes here>
          draft: true
          files: |
            web.zip
            android.aab
