name: Test and build

on:
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_flutter:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          
      - name: Copy .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV > .env

      - name: Get dependencies
        run: flutter pub get

      - name: Install derry
        run: flutter pub global activate derry

      - name: Generate mocks
        run: derry create-mocks

      - name: Run tests
        run: flutter test
  
  build_and_test_functions:
    name: Run tests and build Firebase Functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i

      - name: Run linter
        run: npm run lint
      
      - name: Run functions tests
        run: npm test

  # build_android:
  #   name: Build Android App
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Download Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'

  #     - name: Download Flutter
  #       uses: subosito/flutter-action@v1
  #       with:
  #         channel: 'stable'

  #     - name: Copy google-services.json
  #       env:
  #         FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  #       run: echo $FIREBASE_CONFIG > android/app/google-services.json

  #     - name: Copy keystore
  #       env: 
  #         KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
  #       run: echo $KEYSTORE_BASE64 | base64 -d > android/app/upload-keystore.jks

  #     - name: Copy keystore properties
  #       env:
  #         KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
  #       run: echo $KEY_PROPERTIES > android/key.properties

  #     - name: Print files
  #       run: cd android && ls -R

  #     - name: Get dependencies
  #       run: flutter pub get

  #     - name: Build Android app
  #       run: flutter build apk -v

  build_web:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Copy .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV > .env

      - name: Copy google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > android/app/google-services.json

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web app
        run: flutter build web