on:
  pull_request:
    branches: 
    - master 
name: Test and build
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Download Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'

      - name: Copy google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > android/app/google-services.json

      - name: Get dependencies
        run: flutter pub get

      - name: Build mocks
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test

      - name: Build project (Web + Android)
        run: flutter build web && flutter build apk